name: Publish Docker image
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  prepare-docker-image-build-metadata:
    runs-on: ubuntu-latest
    outputs:
      DOCKER_IMAGE_TAG: ${{steps.prepare-docker-image-build-metadata.outputs.DOCKER_IMAGE_TAG}}
      DOCKER_IMAGE_BUILD_ARG_TELEGRAM_BOT_API_GIT_REF: ${{steps.prepare-docker-image-build-metadata.outputs.DOCKER_IMAGE_BUILD_ARG_TELEGRAM_BOT_API_GIT_REF}}
    steps:
      - name: Check out Telegram Bot API code
        uses: actions/checkout@v4
        with:
          repository: tdlib/telegram-bot-api
          path: telegram-bot-api
      - name: Prepare Docker image build metadata
        id: prepare-docker-image-build-metadata
        run: |
          DOCKER_IMAGE_TAG=$(grep "project(TelegramBotApi VERSION " telegram-bot-api/CMakeLists.txt | cut -d " " -f 3)
          DOCKER_IMAGE_BUILD_ARG_TELEGRAM_BOT_API_GIT_REF=$(cd telegram-bot-api && git rev-parse HEAD | head -1 && cd ..)
          echo "DOCKER_IMAGE_TAG=$DOCKER_IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "DOCKER_IMAGE_BUILD_ARG_TELEGRAM_BOT_API_GIT_REF=$DOCKER_IMAGE_BUILD_ARG_TELEGRAM_BOT_API_GIT_REF" >> $GITHUB_OUTPUT
  build-multiarch-docker-images:
    runs-on: ubuntu-latest
    needs: prepare-docker-image-build-metadata
    strategy:
      matrix:
        platform:
          - linux/386
          - linux/amd64
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64
          - linux/ppc64le
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{matrix.platform}}
          build-args: TELEGRAM_BOT_API_GIT_REF=${{needs.prepare-docker-image-build-metadata.outputs.DOCKER_IMAGE_BUILD_ARG_TELEGRAM_BOT_API_GIT_REF}}
          cache-to: type=local,dest=docker-image-build-caches/${{matrix.platform}},mode=max
      - name: Upload Docker image build caches
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-build-caches
          path: docker-image-build-caches
  publish-docker-image:
    runs-on: ubuntu-latest
    needs: [prepare-docker-image-build-metadata, build-multiarch-docker-images]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Download Docker image build caches
        uses: actions/download-artifact@v4
        with:
          name: docker-image-build-caches
          path: docker-image-build-caches
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{github.token}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: |
            linux/386
            linux/amd64
            linux/arm/v6
            linux/arm/v7
            linux/arm64
            linux/ppc64le
          build-args: TELEGRAM_BOT_API_GIT_REF=${{needs.prepare-docker-image-build-metadata.outputs.DOCKER_IMAGE_BUILD_ARG_TELEGRAM_BOT_API_GIT_REF}}
          cache-from: |
            type=local,src=docker-image-build-caches/linux/386
            type=local,src=docker-image-build-caches/linux/amd64
            type=local,src=docker-image-build-caches/linux/arm/v6
            type=local,src=docker-image-build-caches/linux/arm/v7
            type=local,src=docker-image-build-caches/linux/arm64
            type=local,src=docker-image-build-caches/linux/ppc64le
          push: ${{github.event_name != 'pull_request'}}
          tags: |
            ghcr.io/${{github.repository_owner}}/telegram-bot-api:${{needs.prepare-docker-image-build-metadata.outputs.DOCKER_IMAGE_TAG}}
            ghcr.io/${{github.repository_owner}}/telegram-bot-api:latest
