name: Publish Docker image
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Check out Telegram Bot API code
        uses: actions/checkout@v3
        with:
          repository: tdlib/telegram-bot-api
          path: telegram-bot-api
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker image
        id: build-docker-image
        run: |
          DOCKER_IMAGE_REPO=${{secrets.DOCKER_USERNAME}}/telegram-bot-api
          DOCKER_IMAGE_TAG=$(grep "parameters->version_ = " telegram-bot-api/telegram-bot-api/telegram-bot-api.cpp | head -1 | grep -Eo "[0-9]+(\.[0-9])+")
          DOCKER_IMAGE_TAG_HTTP_CODE=$(curl -sL -w "%{http_code}" -o /dev/null https://hub.docker.com/v2/repositories/$DOCKER_IMAGE_REPO/tags/$DOCKER_IMAGE_TAG/)
          sudo docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}}
          sudo docker buildx create --use
          sudo docker buildx build \
            --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8 \
            --build-arg GIT_COMMIT_HASH=$(cd telegram-bot-api && git rev-parse HEAD | head -1 && cd ..) \
            $([[ ${{github.event_name}} != "pull_request" && $DOCKER_IMAGE_TAG_HTTP_CODE == 404 ]] && echo "--push") \
            --tag $DOCKER_IMAGE_REPO:$DOCKER_IMAGE_TAG \
            --tag $DOCKER_IMAGE_REPO:latest \
            .
